project_id = "yexkjncjuaeoaoimtoxn"

[functions.rent-prediction]
verify_jwt = true

[functions.book-visit]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.webhook-stripe]
verify_jwt = false

[functions.generate-rent-agreement]
verify_jwt = true

[functions.send-message]
verify_jwt = true

[functions.aggregate-stats]
verify_jwt = false

[functions.rent-prediction]
verify_jwt = false

[functions.book-visit]
verify_jwt = false
